### ISSUE TITLE
Some tables break the max. page width and overlap with navigation

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#21]
Some tables break the max. page width and when scrolling, they're overlapped by the right-hand navigation. See e.g. the API Boilerplate chapter in the spec:

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/e91d64b1-d729-46ea-9879-5ccc33414890)

Probably not easy to fix though.

**Comment by oddhack** [comment]
There are some pretty long tokens involved. One option might be to automate something OpenCL does, inserting non-breaking space characters in tokens at opportune points like underscores and camelCase changes. Since all the API entities are marked up using custom macros, we could at least rewrite the extension names and API enum / command / structure names this way, although it would also have consequences on the rest of the spec since that uses the same macros (quite possibly, desirable consequences).

**Comment by oddhack** [comment]
Another possibility would be refactoring some of the tables, but we'd have to assess all the problematic ones. This also gets to the topic of whether the main content pane should or should not widen to fit the available window, which there are opposed views on.

**Comment by oddhack** [comment]
The UI PR just accepted will *affect* this (after the next site update, which will probably be 2024-02-02) but I'm not sure if it actually *closes* it - probably not since it won't do anything for people with narrow windows / displays. Actually eliminating the problem is likely to require refactoring the problematic tables in some fashion, or adding auto-breaking of long tokens as I mentioned above.
