### ISSUE TITLE
Spec/Latest - 404 and possible other issues

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/Vulkan-Site#30]
These issues cover the spec/latest area of docs.vulkan.org:

### Other issues:
There are two large pages on the site, assume this in known:
**Image Operations :: Vulkan Documentation Project Demo**	
https://docs.vulkan.org/spec/latest/chapters/textures.html
Size: 4.7 MB

**Drawing Commands :: Vulkan Documentation Project Demo**	
https://docs.vulkan.org/spec/latest/chapters/drawing.html
4.3 MB

### 404 Errors:

https://docs.vulkan.org/spec/latest/proposals/proposals/VK_EXT_graphics_pipeline_library.html
Links to non-existent page:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_ray_tracing.html

https://docs.vulkan.org/spec/latest/proposals/proposals/VK_GOOGLE_surfaceless_query.html
Links to non-existent page:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurface.html

https://docs.vulkan.org/spec/latest/appendices/extensions.html
Links to non-existent page:
https://github.com/KhronosGroup/GLSL/blob/master/extensions/qcom/GLSL_QCOM_image_processing2.txt

https://docs.vulkan.org/spec/latest/appendices/extensions.html
Links to non-existent page in 2 places:
https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_cooperative_matrix.txt

**Comment by oddhack** [comment]
3/4 of those are fixed in Vulkan-Docs. The fourth is a dangling reference to what I suspect is an as-yet unpublished GLSL extension - will check with them. N.b. all these dead links should show up in the current Vulkan registry as well, there's nothing Antora-specific about them.

The large pages are a consequence of the Antora "page" being equivalent to a Vulkan spec chapter, which is the highest structural element short of the spec itself. We could fix them but that would require splitting the chapter, which is a WG decision for later - there is literally no workaround for this possible AFAIK.

**Comment by oddhack** [comment]
@KhronosWebservices I propose closing this - there's a tracker for the large page issue and the remaining markup issue will be fixed once the vendor responsible for that language responds to the internal tracker I created. Thanks for the checkup! We probably should run it on a semiregular basis. Unfortunately virtually all dead link issues are going to require fixes in the separate repos for the corresponding components.

**Comment by KhronosWebservices** [comment]
SGTM, thank you.
