### ISSUE TITLE
Poor readability of grey text on grey background in VU boxes

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Site#56]
Moving this issue over from the archived Antora repo (https://gitlab.khronos.org/vulkan/antora/-/issues/3 per @daniel-story). Note: there are some comments in the archived repo on this issue..

I'm not sure if this is the correct place for internal issues related to the new Vulkan Documentation Project Demo site, but I wanted to call attention to the somewhat poor contrast of text vs. background in the VU boxes on the new site. VUs are already notoriously dense in terms of both verbiage and actual information content, so I would like to suggest a lighter background color for VU boxes.

**Comment by oddhack** [comment]
Two points brought up in discussion this week:

- This is a special case of the general accessibility question. Low contrast is an accessibility issue. We have some intention to hire an accessibility consultant as this is, broadly speaking, beyond our competency.
  - I've used the ANDI tool (https://www.ssa.gov/accessibility/andi/help/howtouse.html) with some success on the asciidoctor-generated specs. @outofcontrol also has a tool used for this sort of thing, though my attempt to run it on the enormous single-page Vulkan spec made that fall over and die - it will probably be fine for the Antora site pages, though.
- While easily changed in the site CSS, also note Antora renders VU blocks differently than straight asciidoctor, which puts this type of block into a box, rather than using highlighting. Having some way to visually identify the VU blocks would help when making them collapsible, as we expect to eventually do. So just removing the gray-on-gray CSS would not accomplish that.

**Comment by oddhack** [comment]
Fixed link to internal gitlab site.

**Comment by oddhack** [comment]
Proposed fix linked above. I'd prefer we just take that without getting bogged down on related CSS tweaks - it is clearly an improvement IMO and addresses the actual issue, even if further improvement is possible.
