### ISSUE TITLE
Separation of proposals and Specification?

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Site#59]
Moved over from Antora repo...from Tobias:

Currently the docs website has the proposals lumped under the spec documentation, and it's kind of a weird place for them as they're all sitting at the end as a long collapsed list of extensions.

IMO it would be good to have these separated out to a separate page so they can be found more prominently. We may also want to consider how they're labelled - something like "Feature Overviews" would be a useful direction to move in I think.

**Comment by oddhack** [comment]
It was a judgement call as to whether to combine them with the spec Antora "component" and I'm happy to do it the other way, though it will require a bit more setup in the scripts.

@tobski may want to comment on your proposed renaming. I think they are called "Proposals" because that's literally what they are, leading to later specs. If we want "feature overviews" that are more in-depth than the Overview section of the extension appendices, that is probably a task for the technical writer.

**Comment by oddhack** [comment]
BTW it is possible to literally move an issue between repos in github - see the "Transfer issue" link on the bottom-right. Though you may need admin privileges on one or both repos - not sure about that. But it does preserve history of the issue.

**Comment by oddhack** [comment]
Duplicates #54
