### ISSUE TITLE
Extension proposal for VK_KHR_dynamic_rendering_local_read not accessible from navigation

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#68]
Oddly the extension proposal for `VK_KHR_dynamic_rendering_local_read` is not listed in the navigation under "extension proposals". It is there and can be reached via the search though.

Link: https://docs.vulkan.org/spec/latest/proposals/proposals/VK_KHR_dynamic_rendering_local_read.html

**Comment by oddhack** [comment]
I'll need to update the antora-prep script to regenerate modules/proposals/nav.adoc - there are many more proposals now that in the list there, which is a static file that has not been updated since last April.

**Comment by oddhack** [comment]
This has been fixed in the Vulkan internal repo and will show up in the next spec update - nav.adoc in the proposals module is now generated dynamically from the actual proposal files present.

**Comment by oddhack** [comment]
> This has been fixed in the Vulkan internal repo and will show up in the next spec update - nav.adoc in the proposals module is now generated dynamically from the actual proposal files present.

N.b. there was some discussion on the call today about the left sidebar "Extension Proposals" section in the proposals module expanding to a [very long list](https://docs.vulkan.org/spec/latest/proposals/proposals/VK_AMDX_shader_enqueue.html) now, which was an unavoidable consequence of updating the module to include all the proposals. The only way to avoid it I can see is to move the proposals into subsections of a single page instead of being separate pages, in which case the *right* sidebar navigation on that page would get very long, instead - like the [right sidebar](https://docs.vulkan.org/spec/latest/appendices/extensions.html) in the "Layers & Extensions" appendix of the spec, where all 300-odd extensions are included, and it takes a second or two to generate the sidebar. At least this way, the left sidebar section is normally collapsed.
